name: Automated Build

env:
  DOCKERHUB_REPO: flyskype2021/apollo-quick-start

# Trigger on release
on:
  push:
    branches:
    - master

jobs:
  build:

    name: build
    
    runs-on: ubuntu-latest

    steps:
      - name: Generate Docker image labels
        uses: crazy-max/ghaction-docker-meta@v2.5.0
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          label-custom: |
            maintainer=flyskype2021
            org.opencontainers.image.title=apollo-quick-start
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      
      - uses: actions/checkout@master
      
      - name: Sync README To DockerHub
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{secrets.REGISTRY_USERNAME}}
          pass: ${{secrets.REGISTRY_PASSWORD}}
          slug: ${{ env.DOCKERHUB_REPO }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64,linux/arm/v7
          pull: true
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
          labels: ${{ steps.docker_meta.outputs.labels }}
